### PR TITLE
fix typo in previously merged bash script & add fish script for nerds who use fish

### PR DESCRIPTION
**Pull request by Izder456**
i use fish and someone who uses fish might find this useful.

### CODE REVIEW

**Comment by Sterophonick** [comment]
Actually are all these scripts necessary? Users can just use make, right?

**Comment by Izder456** [comment]
> Actually are all these scripts necessary? Users can just use make, right?

not really but fish could be useful for someone who uses fish (like me)

**Comment by Izder456** [comment]
you might want to just merge the typo fix though. That is if you don't want fish.

**Comment by Sterophonick** [comment]
yeah, i realized that using `make` works just fine for any platform. closing this,

**Comment by Sterophonick** [comment]
Thanks for your proposals anyway.

**Comment by Izder456** [comment]
no it's fine

**Comment by Izder456** [comment]
@Sterophonick, you might want to update README with new build instructions

**Comment by Sterophonick** [comment]
I did.

**Pull request closed without merging**
